build.sh
src/api/plugin/tr50/tr50.c
src/device-manager/device_manager_file.h
src/device-manager/device_manager_main.c
test/mock/mock_osal.c

This patch contains a fix to the build script to build using the
open-source OSAL layer instead of trying to use one in a private
repository with a private key.

build: fix to open with open-source osal layer

---

src/api/plugin/tr50/tr50.c

closes: #57
The tr50 plug-in code worked assuming all actions were initiated by the
cloud.  This is not the case, by call iot_action_execute directly one is
able to similate and action locally.  However, doing this was causing a
seg fault as the action was trying to update the cloud with a result.
This patch provides a fix that disables this update as intended.

tr50: executing non-cloud based actions causes segfault

---

src/api/iot_mqtt.c

Memory being allocated by paho mqtt client library was not being free'd
after being used.  This patch adds the required free commands to ensure
that memory is free'd after use.

api: fix memory leaks caused by paho

---

src/api/public/iot_plugin.h

The internal macro for generating plug-in functions expected the _load
function to return an "iot_bool_t".  However, when not using a plug-in the
macro was generating code with a function that returns a "void".  This
patch updates the code so that it is all consistent.

api: fixes to plug-in function signatures

---

CMakeLists.txt
build-sys/cmake/modules/OptionSelect.cmake

This patch add a function to cmake to ensure that an option will always
have a value set even if give a blank -D value on the command line.
For example: "cmake -DIOT_THREAD_SUPPORT:BOOL= ." was setting the value
IOT_THREAD_SUPPORT to a value of "" which would make it not be set to
the default value of "ON".  This fix ensures that this variable will be
either OFF, ON, or an explicitly set value on the command line.

build: add option to ensure that a value is set

---

src/device-manager/device_manager_main.c

Previously the API version was being published to an attribute named:
`device-cloud_version`, however, this was not in the thing definition.
The thing definition contained an item named: `hdc_version`, but the
project is in the process of removing the `hdc` name.  This patch
updates the attribute to be published as the property `api_version` so
that the property is now name agnostic.

device-manager: publish api version to api_version

---

src/api/plugin/tr50/tr50.c

Setting the log level to "TRACE", causes a lot of output as expected
that isn't totally helpful to non-developers.  However, setting it up a
level to "DEBUG", causes not enough information to see if there are
messages going in and out of the system.  This patch updates the code to
show raw messages that come in and out on the DEBUG level, so that there
is a good level of intermediate of information being produced.  If this
isn't desired than a user can set the level higher to "INFO".

api: show receive/send messages as debug

---

src/api/iot_base.c
src/api/iot_mqtt.c
src/api/iot_plugin.c
src/api/plugin/tr50/tr50.c
src/api/public/iot.h
src/api/public/iot_mqtt.h
src/api/public/iot_plugin.h
src/api/shared/iot_types.h
test/unit/api/iot_base_test.c
test/unit/mock/mock_osal.c
test/unit/mock/mock_osal.cmake

This commit contains a few fixes in 2 main areas.
1)  This adds the api `iot_transaction_status` which allows the user to be able to see the status of a publish of a telemetry, attribute, or event...  when the cloud has handled that piece of information
2) This fixes connection issues that are experienced after being alive for long periods of time, but fixing the underlying mqtt sub-system.

Transaction support + MQTT connection stabilzation

---

share/admin-tools/app_defs/demo_apps.cfg

fixes: #100
The complete app is being removed.  The thing def does not exist
so remove the app def as well.
Signed-off-by: Paul Barrette <paulbarrette@gmail.com>

admin_tools: remove complete app from app cfg

---

src/control/control_config.c
src/control/control_config.h
src/control/control_main.c
src/device-manager/device_manager_main.c
src/relay/relay_main.c
src/utilities/app_arg.c
src/utilities/app_arg.h
test/test-support/CMakeLists.txt
test/unit/CMakeLists.txt
test/unit/utilities/CMakeLists.txt
test/unit/utilities/app_arg_test.c
test/unit/utilities/app_log_test.c
test/unit/utilities/app_path_test.c

This patch set contains fixes to mainly to the argument parsing utility.
Mainly, it includes fixes to the following areas:
1) adds the ability to specify for a configuration file to generate using iot-control
2) adds an iterator for iterating through command line arguments
3) updates the current routines argument parser to utilize new iterator routines which will allow for future support of defining the same argument multiple times
4) ports unit tests from the old repository code to the new code repository to ensure that the code continues to work as expected.

update argument parser support utility & port some unit tests from old repo

---

src/api/plugin/tr50/tr50.c

fixes: #103
When publishing a timestamp in a tr50 message, the milliseconds where
just being added as the number of milliseconds.  However, this was
misleading as on the cloud, as 1 or 2 digit milliseconds where missing
leading 0's.  For example, .57 was being represented instead of the
intended .057.  This causes the cloud to not show the events in the
correct order.

tr50: always use 3 digits for milliseconds

---

build.sh

fixes: 92
This patch updates the build script to handle the case that cmocka is
not available for download (or that wget is not installed).  This may
happen when running the build on a relatively clean "ubuntu" docker
image.

build: handle cmocka not found

---

src/api/iot_base.c
test/unit/mock/mock_osal.c

fixes: 113
Previously there was an error reading the device_id file containing an
id < 36 characters and containing a "new-line" character.   The MQTT
connections was using the new-line character as part of the client id,
causing the connection to not be accepted by the cloud.  This patch
fixes the reading to test if there are any valid ascii characters in the
device id file.

api: handle short device id's

---

.travis.yml
build.sh
src/api/json/iot_json_decode.c
test/test-support/test_support.c
test/test-support/test_support.h
test/unit/api/iot_action_test.c
test/unit/api/iot_base_test.c
test/unit/api/iot_common_test.c
test/unit/mock/mock_osal.c

This includes 2 patches...
1) Add declarations to the test-support library to allow unit tests written for: cmocka 1.0 tests to run under cmocka 0.3.2...  (this is because travis running Ubuntu 14.04, can install cmocka 0.3.2 as a package.  reducing the need to build it for every use)
2) It updates the build.sh script to only build the dependent packages that it requires.  This allows the automated builds to be slightly faster.

Build fixes

---

build.sh

fixes: #105 
This patch updates the build script to exit on any critical  error.
This helps us to diagnose why/where exactly where the script fails.

build: exit on build error

---

src/device-manager/device_manager_main.c
src/device-manager/device_manager_main.h
src/device-manager/iot.cfg.example

Resolves: #120  
This patch adds support for publishing the
remote_access_support attribute from the config file
to the cloud, in the form of a JSON string.
Also checks that the ports specified are active
before publishing.

device-manager: 'remote-access-support' cfg support

---

src/device-manager/iot.cfg.example

fixes: #109
Changed the iot.cfg.example to be valid JSON and removed the
"remove_on_upload_success" attribute which is currently not
supported in the C library. Also added RDP to the remote access
support list.

device-manager: iot.cfg.example changes

---

src/device-manager/device_manager_main.c

A recent change in the OSAL layer is causing the Android build to fail
due to mismatch of parameters.  This patch fixes the parameters to
match.

build: fix for android build

---

src/device-manager/device_manager_main.c

Fixes a bug where a port being checked was being incorrectly marked as inactive.

device manager: check listening port fix

---

src/api/iot_action.c
src/api/iot_base64.c
src/api/iot_common.c
src/api/plugin/tr50/tr50.c
src/api/shared/iot_base64.h
test/unit/api/CMakeLists.txt
test/unit/api/iot_base64_test.c

fixes: #114
This patch adds a basic conversion from string to raw type inside the
library.  This this noticed when incoming parameters are registered as
"raw types" but are sent in base64 string values from the cloud.  This
allows for the internal conversion from base64 strings to raw data.

api: add conversion from string to raw

---

src/device-manager/device_manager_main.c

fixes: #133
On Android there is not such thing as the "sudo" command.  Running an
operating system command as privileged attempts to run commands by
prefixing "sudo".  This patch indicates not the run the operating system
command code in privileged mode, thus removing the addition of "sudo" to
the command.

android: do not run system commands as priviledged

---

src/api/CMakeLists.txt
src/api/iot_action.c
src/control/CMakeLists.txt
src/device-manager/CMakeLists.txt
src/device-manager/device_manager_main.c
src/device-manager/device_manager_ota.c
src/relay/CMakeLists.txt
src/update/CMakeLists.txt
src/update/update_main.c
test/unit/api/iot_action_test.c
test/unit/mock/mock_osal.c
test/unit/mock/mock_osal.cmake

This patch updates the source code to use the new `os_system_run`
signature that was updated in the OSAL layer.  This will help to
integrate better across multiple platforms.
[NOTE BUILD WILL FAIL BECAUSE OF CHANGE IN OSAL SIGNATURE!]

system_run: use updated os_system_run signature

---

build-sys/vxworks-lib/control/Makefile
build-sys/vxworks-lib/device-manager/Makefile
build-sys/vxworks-lib/lib/vxworks.krnl.mak
build-sys/vxworks-lib/lib/vxworks.lib.mak
build-sys/vxworks-lib/relay/Makefile

This patch updates the build scripts to build again for VxWorks 7.
Recent commits didn't update the build system for VxWorks.

vxworks: fixes to build on VxWorks 7

---

src/api/plugin/tr50/tr50.c
src/device-manager/device_manager_main.c
src/device-manager/device_manager_main.h
src/device-manager/iot.cfg.example
src/relay/CMakeLists.txt
src/relay/relay_main.c
src/utilities/app_json_base.c
src/utilities/app_json_decode.c

This patch set contains multiple fixes.
1) Certificate information is now passed via the command line when calling `iot-relay`.  This is useful, if the device manager is configured to use private certificates.  In this major, `iot-relay` will also use the same private certificate when connecting with the cloud.  Previously, `iot-relay` was trying to read this information from `/etc/iot/iot-connect.cfg`.  However, if the private certificate was specified in `/etc/iot/device-manager.cfg`, the `iot-relay` wouldn't pick up the new path.
2) Memory leak fixes.  There we memory leak fixes throughout the `iot-device-manager` that are fixes.  When running under Linux & Valgrind, it now shows 0 memory leaks.
3) General code clean-up.  The relay_client (the main method inside `iot-relay) app, now …

Relay cert
